language: java
sudo: false
jdk:
    - openjdk8
before_install:
- cp .travis.settings.xml $HOME/.m2/settings.xml
install: mvn install -Dbasepom.check.skip-dependency-versions-check=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
script: mvn test -B -V 
deploy:
  provider: script
  script: "mvn -B -q -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DskipTests=true deploy"
  skip_cleanup: true
  on: 
    tags: false
    jdk: openjdk8
cache:
  directories:
  - $HOME/.m2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ada7bbc05b2a99cff40
    on_success: change
    on_failure: always
    on_start: never